-- Criação das tabelas

create table tb_category (
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone,
    name varchar(255),
    primary key (id)
);

create table tb_user (
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone,
    email varchar(255),
    name varchar(255),
    password varchar(255),
    phone varchar(255),
    primary key (id)
);

create table tb_product (
    id bigint generated by default as identity,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    name varchar(255),
    description varchar(255),
    img_url varchar(255),
    price float(53),
    quantity_in_stock integer,
    primary key (id)
);

create table tb_product_category (
    category_id bigint not null,
    product_id bigint not null,
    primary key (category_id, product_id)
);

create table tb_order (
    id bigint generated by default as identity,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    moment timestamp(6) with time zone,
    client_id bigint,
    order_status integer,
    payment_method smallint check (payment_method between 0 and 1),
    primary key (id)
);

create table tb_order_item (
    order_id bigint not null,
    product_id bigint not null,
    quantity integer,
    price float(53),
    primary key (order_id, product_id)
);

create table tb_payment (
    order_id bigint not null,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    moment timestamp(6) with time zone,
    payment_method integer check (payment_method in (0, 1)),
    primary key (order_id)
);

-- Restrições de chave estrangeira

alter table if exists tb_order
    add constraint FKi0x0rv7d65vsceuy33km9567n foreign key (client_id) references tb_user;

alter table if exists tb_order_item
    add constraint FKgeobgl2xu916he8vhljktwxnx foreign key (order_id) references tb_order;

alter table if exists tb_order_item
    add constraint FK4h5xid5qehset7qwe5l9c997x foreign key (product_id) references tb_product;

alter table if exists tb_payment
    add constraint FKokaf4il2cwit4h780c25dv04r foreign key (order_id) references tb_order;

alter table if exists tb_product_category
    add constraint FK5r4sbavb4nkd9xpl0f095qs2a foreign key (category_id) references tb_category;

alter table if exists tb_product_category
    add constraint FKgbof0jclmaf8wn2alsoexxq3u foreign key (product_id) references tb_product;

-- Inserção de categorias

insert into tb_category (created_at, updated_at, name) values
(now(), now(), 'Tecnologia STAR Labs'),
(now(), now(), 'Análises e Registros'),
(now(), now(), 'Equipamentos de Viagem no Tempo');

-- Inserção de usuários

insert into tb_user (id, created_at, updated_at, email, name, password, phone) values
(1, now(), now(), 'barry@starlabs.com', 'Barry Allen', '123456', '988888888'),
(2, now(), now(), 'cisco@starlabs.com', 'Cisco Ramon', '123456', '977777777');

-- Inserção de produtos

insert into tb_product (price, quantity_in_stock, created_at, updated_at, description, img_url, name) values
(4500.0, 200, now(), now(), 'Uniforme usado por Barry Allen para correr em alta velocidade.', '', 'Traje do Flash'),
(1800.0, 200, now(), now(), 'Dispositivo criado por Cisco Ramon para acessar outras dimensões.', '', 'Óculos de Vibração'),
(25000.0, 200, now(), now(), 'Dispositivo usado por Barry para viagens no tempo.', '', 'Esfera Temporal'),
(3200.0, 200, now(), now(), 'Arma tecnológica desenvolvida por Cisco na Star Labs.', '', 'Luva de Energia'),
(250.0, 200, now(), now(), 'Anotações científicas essenciais para a equipe Flash.', '', 'Diário do Harrison Wells');

-- Inserção de relações produto-categoria

insert into tb_product_category (category_id, product_id) values
(2, 1),
(1, 2),
(3, 2),
(3, 3),
(1, 4),
(2, 5);

-- Inserção de pedidos

insert into tb_order (order_status, payment_method, client_id, created_at, moment, updated_at) values
(1, 0, 1, now(), '2025-03-15 10:30:00+00', now()), -- Créditos Temporais
(2, 1, 2, now(), '2025-04-10 14:45:00+00', now()), -- Sincronização Quântica
(2, 1, 1, now(), '2025-05-05 08:20:00+00', now());

-- Inserção de itens de pedidos

insert into tb_order_item (price, quantity, order_id, product_id) values
(4500.0, 2, 1, 1),
(25000.0, 1, 1, 3),
(25000.0, 2, 2, 3),
(250.0, 2, 3, 5);

-- Inserção dos pagamentos

insert into tb_payment (payment_method, created_at, moment, order_id, updated_at) values
(0, now(), '2025-03-15 12:30:00+00', 1, now()), -- Créditos Temporais 1
(1, now(), '2025-04-10 16:00:00+00', 2, now());  -- Sincronização Quântica 2







----------------------------------------------------------------------------------------


